feat: [LI-186] add api hook and error page for get candidate schedule link info
PredictiveHire/phapp-schedule-link pull request #14
Opened 2024-07-09 01:02 UTC by lulu0729

### Issue ticket number and link
[LI-186](https://predictivehire.atlassian.net/browse/LI-186)
### Figma Screenshot
<img width="1749" alt="image" src="https://github.com/PredictiveHire/phapp-schedule-link/assets/34208317/6bdeede8-7242-4eb0-9c94-8eda61167217">

### Describe main changes
- Add API hook for `getCandidateScheduleLinkInfoByShortcode`
- Add error page
- Unit test
### Checklist in Local 
- [x] I have extract component business logic into custom hook
- [x] I have added unit tests
- [x] I have integrated with backend api and done a e2e test locally
- [x] I have updated the graphql query types

#### Screenshots for Integration Test in Local

https://github.com/PredictiveHire/phapp-schedule-link/assets/34208317/2839f5d8-6190-4dee-ad90-0f0bae46d85f

### Checklist in Dev
- [ ] I have deployed to dev
- [ ] I have integrated with backend api and done a e2e test

#### Screenshots for Integration Test in dev

### Checklist before requesting a review
- [ ] I have done the **code format** using `pnpm lint:fix` and `pnpm format:fix`
- [ ] I have **rebase squash** current branch
- [ ] I have confirmed **Naming Convention** with team if needed.
- [ ] I have done a **self review** in GitHub.

### Checklist in Qa Environment
- [ ] I have deployed to qa and let QA team do a test
- [ ] I have fix the QA bugs after QA team finish testing
- [ ] I have put the screenshot for Qa environment integration test below:

#### Screenshots for Integration Test in Qa

### Checklist in Sandbox Environment
- [ ] I have deployed to sandbox and let QA team do test
- [ ] I have fix the Sandbox Bugs after QA team finish testing
- [ ] I have put the screenshot for Qa environment integration test below:

#### Screenshots for Integration Test in Sandbox

### Checklist after Merge
- [ ] I have known the dependencies of release deployment of current PR.
- [ ] I have reviewed the release pipe from team lead to secure the production deployment.
- [ ] I have update the Jira tickets status after all task has been finished.

2024-07-10 00:53 UTC, GeekEast commented on src/components/InvalidPage/InvalidPage.tsx
> +export const InvalidPage: React.FC<InvalidPageProps> = ({ description }) => {
rename this one as `ErrorPage`

2024-07-10 00:54 UTC, GeekEast commented on src/components/THLoading/THLoading.tsx
> +export const THLoading = ({ heightClass = "h-full" }: { heightClass?: string }) => {
What does `TH` in `ThLoading` mean here?

2024-07-10 00:54 UTC, GeekEast commented on src/components/THLoading/THOnTopLoading.tsx
> +export const THOnTopLoading = () => {
TH

2024-07-10 00:55 UTC, GeekEast commented on src/pages/schedule-interview/components/CandidateScheduleError/index.ts
this one is empty?

2024-07-10 00:56 UTC, GeekEast commented on src/pages/schedule-interview/components/CandidateScheduleError/CandidateScheduleError.tsx
> +  } else {
you need to check the specific error code for case`closed for booking`

don't just use `else` here especially in future you will have more case check.

2024-07-10 00:58 UTC, GeekEast commented on src/pages/schedule-interview/components/CandidateScheduleError/CandidateScheduleError.tsx
> +  const code = getCandidateScheduleLinkInfoError?.graphQLErrors[0]?.extensions?.code
you already use `useScheduleInterview` in `ScheduleInterview.tsx`

you just need to pass code into the `CandidateScheduleError`

2024-07-10 01:00 UTC, GeekEast commented on src/pages/schedule-interview/context/ScheduleInterviewContext.tsx
> +  const [interviewInfo, setInterviewInfo] = useState({} as CandidateInterviewScheduleInfo)
better to use `useState<CandidateInterviewScheduleInfo>()`

why the default value is `{}` rather than `null`

2024-07-10 01:05 UTC, GeekEast commented on src/pages/schedule-interview/context/ScheduleInterviewContext.tsx
> +        setCandidateInterviewScheduleStatus(candidateScheduleStatus as LICandidateInterviewScheduleStatus)
why need to do compulsory type `as`?

2024-07-10 01:05 UTC, GeekEast requested changes
Hi @lulu0729 I've left some comments. Please have a look.

2024-07-10 03:52 UTC, bennyli519 commented on src/pages/schedule-interview/context/ScheduleInterviewContext.tsx
> +        } = candidateScheduleLinkInfo as LiCandidateScheduleLinkInfo
why need to `as` here

2024-07-10 03:52 UTC, bennyli519 commented on src/pages/schedule-interview/context/ScheduleInterviewContext.tsx
> +          iCalId: interviewEvent.iCalId ?? "",
iCalId is required info as well as `interviewStartsAt` and `interviewEndsAt`

2024-07-11 00:48 UTC, lulu0729 commented on src/pages/schedule-interview/context/ScheduleInterviewContext.tsx
> +        } = candidateScheduleLinkInfo as LiCandidateScheduleLinkInfo
Because the fields like`start` and `end` are converted to `any` type, we are casting them to `LiCandidateScheduleLinkInfo` to ensure they are of type `string` or `null`.

2024-07-11 00:49 UTC, lulu0729 commented on src/pages/schedule-interview/context/ScheduleInterviewContext.tsx
> +          iCalId: interviewEvent.iCalId ?? "",
When the candidate status is `pending`, there is no `interviewEvent`. In this case, `iCalId`, `interviewStartsAt`, and `interviewEndsAt` are all `null`

2024-07-11 01:26 UTC, GeekEast approved these changes
LGTM! Please push to dev environment to have a integration testing.

2024-07-12 00:04 UTC, bennyli519 commented on src/pages/schedule-interview/context/ScheduleInterviewContext.tsx
> +          iCalId: interviewEvent.iCalId ?? "",
got it

2024-07-12 06:27 UTC, merged